### ISSUE TITLE
'libpng12-dev' error with Ubuntu > 16.04

### ISSUE THREAD

**Issue by mujahidi** [suthanbala/wordpress-docker-gulp#6]
The package `libpng12-dev` was dropped after Ubuntu 16.04. Hence, I had to use `libpng-dev`. 

https://github.com/suthanbala/wordpress-docker-gulp/blob/b703492234ff96f1df3c10c9997ac9223f28abfc/Dockerfile#L6

**Comment by suthanbala** [comment]
Thanks mujahidi. Added the fix,
