### ISSUE TITLE
Error connecting to MySQL

### ISSUE THREAD

**Issue by nickpish** [suthanbala/wordpress-docker-gulp#7]
First off, thank you for this repo- it's exactly what I'm looking for to streamline my local WP dev. I'm experiencing an issue w/ MySQL when trying to build the containers (using Docker on Windows), right out-of-the-box, so to speak, with no edits to your files. I'm getting the following:

```
MySQL Connection Error: (2002) Connection refused
wp            |
wp            | Warning: mysqli::mysqli(): (HY000/2002): Connection refused in - on line 10
wp            |
wp            | MySQL Connection Error: (2002) Connection refused
wp            | Warning: mysqli::mysqli(): (HY000/2054): Server sent charset unknown to the client. Please, report to the developers in - on line 10
```
I've attempted numerous fixes, including changing the version of the MySQL image, adding the line `command: '--default-authentication-plugin=mysql_native_password'` to the `docker-compose` file as detailed [here](https://github.com/docker-library/wordpress/issues/313) along with other tweaks, but nothing has worked. It seems the solution might lie [here](https://stackoverflow.com/questions/49948350/phpmyadmin-on-mysql-8-0) but I'm not sure the best way to implement this approach with your scripts.

Thanks for any assistance here- would love to get your rig going!

**Comment by suthanbala** [comment]
Please pull the latest codebase, rebuild. It should all work normal.
